In [1]:
from tkinter import *
import numpy as np
import pandas as pd
from fuzzywuzzy import fuzz
from sklearn import tree
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

ModuleNotFoundError: No module named 'fuzzywuzzy'

In [ ]:
tr_df=pd.read_csv("diab.csv")

In [ ]:
tr_df.head(5)

In [ ]:
tr_df["output"] = tr_df["output"].replace(['No_Diabetes','Prediabetis','Type1','Type2'],[0,1,2,3])

In [ ]:
tr_df.head()

In [2]:
tr_X=tr_df.iloc[:,:-1]
tr_y=tr_df.iloc[:,-1:]

NameError: name 'tr_df' is not defined

In [3]:
tr_Xtrain,tr_Xtest,tr_ytrain,tr_ytest = train_test_split(tr_X,tr_y,test_size = 0.2,random_state = 0)

NameError: name 'train_test_split' is not defined

In [4]:
import lightgbm as lgb

ModuleNotFoundError: No module named 'lightgbm'

In [5]:
d_train = lgb.Dataset(tr_Xtrain, label=tr_ytrain)

NameError: name 'lgb' is not defined

In [174]:
params = {}
params['learning_rate'] = 0.003
params['boosting_type'] = 'gbdt'
params['objective'] = 'multiclass'
params['metric'] = 'multi_logloss'
params['num_class'] = 4
params['sub_feature'] = 0.5
params['num_leaves'] = 200
params['min_data'] = 50
params['max_depth'] = 10

In [175]:
clf = lgb.train(params, d_train, 500)

In [176]:
tr_pred = clf.predict(tr_Xtest)

In [177]:
print(tr_pred)

[[0.95714983 0.03359911 0.00734982 0.00190125]
 [0.95714983 0.03359911 0.00734982 0.00190125]
 [0.2030242  0.0734466  0.71918446 0.00434474]
 ...
 [0.95714983 0.03359911 0.00734982 0.00190125]
 [0.95714983 0.03359911 0.00734982 0.00190125]
 [0.95714983 0.03359911 0.00734982 0.00190125]]


In [178]:
print(np.argmax(tr_pred, axis = 1))

[0 0 2 ... 0 0 0]


In [179]:
accuracy = accuracy_score(tr_ytest, np.argmax(tr_pred, axis = 1))*100
print(accuracy)

99.61508852963819


In [180]:
X=pd.read_csv("diabres.csv")

In [181]:
X.head()

Empty DataFrame
Columns: [6.4, 120.0, 6.2]
Index: []

In [182]:
import csv

In [183]:
with open('diabres.csv',newline='') as f:
    reader = csv.reader(f)
    data = list(reader)

In [184]:
print(data)

[['6.4', '120.0', '6.2']]


In [185]:
X_new=[['20.43','368','9.4']]

In [186]:
Y_new = clf.predict(X_new)

In [187]:
print(Y_new)

[[0.2356943  0.08746188 0.13923785 0.53760596]]


In [188]:
y_new = np.argmax(Y_new, axis = 1)

In [189]:
print(y_new)

[3]


In [190]:
if(y_new==0):
    print('No_Diabetes')
elif(y_new==1):
    print('Prediabetis')
elif(y_new==2):
    print('Type1')
else:
    print('Type2')

Type2
